name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - stable*

jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    name: eslint node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
